# Generated by Django 3.1.6 on 2022-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=60)),
                ('race', models.CharField(max_length=60)),
                ('age', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
