# Generated by Django 3.1.6 on 2022-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='spa/photos'),
        ),
    ]
