# Generated by Django 3.1.6 on 2022-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_auto_20220607_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='spa/static/spa_photos'),
        ),
    ]
